services:
  postgres:
    image: postgres:latest
    container_name: postgres-go-digi-wallet
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: digital-wallet
    ports:
      - "5431:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume: